name: Continous deployment job

on: [push, pull_request]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: yarn install
    
    - name: Build
      run: echo "Building..."
    
    - name: 
      run: yarn test

